### PR TITLE
Add basic SwiftPM manifest file

### PR DESCRIPTION
**Pull request by Jeehut**
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.

### CODE REVIEW

**Comment by Dschee** [comment]
@wtmoose Anything holding you off from merging this?

**Comment by wtmoose** [comment]
Yep, I'm busy

**Comment by arnauddorgans** [comment]
SPM support ❤️

**Comment by tbaranes** [comment]
Xcode 11 GM is out, any news from this?

**Comment by wtmoose** [comment]
@tbaranes does this branch work? I was under the impression that SPM didn’t support resource bundles, which would make it incompatible with SwiftMessages.

**Comment by tbaranes** [comment]
Yeah, after posting this message I give it a try in my [own fork](https://github.com/tbaranes/SwiftMessages/), the library itself ended compiling, but not everything is working. As you say, there's no ressources bundle working at the time.

**Comment by wtmoose** [comment]
Partial SPM support added in 8.0.2. See #395 for setup instructions.

**Pull request closed without merging**
