### PR TITLE
Dispatched Presenter.init(config:view:delegate:) call in SwiftMessages class to the main queue

### PR DESCRIPTION
**Pull request by ceyhuno**
`Presenter.init(config:view:delegate:)` initializes a `PassthroughView` instance variable called `maskingView` which is a `UIView` and this triggers a `setNeedsDisplay` call that should be made in the main thread.

### CODE REVIEW

**Comment by wtmoose** [comment]
Good catch on this. Would you mind resetting the head of your branch to your original commit e1725019cf7a94c47853e5a60be12481d03e55da? Looks like you pulled in a commit I accidentally pushed to origin.

**Comment by ceyhuno** [comment]
If you accidentally pushed your latest commit, will you revert it? I merged your branch to my branch because there was a conflict after your latest commit. We'll get a conflict again if I reset it to the original commit.

**Comment by wtmoose** [comment]
Already reverted.

**Comment by ceyhuno** [comment]
OK I resetted my branch too 👍

**Comment by wtmoose** [comment]
Thanks for the fix!

**Comment by ceyhuno** [comment]
🎉 thank you!

**Pull request merged**
