### PR TITLE
Fixes #207

### LINKED ISSUE #207: Haptic Feedback
Maybe it would be a good idea to add some optional haptic feedback to certain alerts.

According to the [human guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/feedback/), there's three levels of feedback for notifications: success, warning and error.

At the moment it can be added using event listeners, but adding default support for it on specific configurations would be helpful

### PR DESCRIPTION
**Pull request by AlbertoSamele**
Added default haptic feedback support, fixes #207

### CODE REVIEW

**Comment by mikestalker** [comment]
@wtmoose can you merge this improvement and release it please?

**Comment by mikestalker** [comment]
Hello. Any chanse to get this PR merged?

**Comment by mikestalker** [comment]
@wtmoose sorry to bother you, but can you give some update regarding status of this library? Almost 1 year since my first comment in this PR and no any updates. Is this library dead?

**Comment by mikestalker** [comment]
@wtmoose ?

**Comment by wtmoose** [comment]
Thanks. There were a few problematic areas that I cleaned up.

**Comment by mikestalker** [comment]
Thanks @AlbertoSamele , thanks @wtmoose 
Works like a charm. Waiting for release.

**Comment by mikestalker** [comment]
@wtmoose sorry to bother you, but do you have some idea when you will release this feature?

**Comment by wtmoose** [comment]
Now

**Pull request merged**
