### PR TITLE
Compatible with x86_64 ach for M1.

### PR DESCRIPTION
**Pull request by m-afham**
- Added x86_64 architecture.
- On M1, when trying to run on the simulator it gives an error "missing x86_64 architecture".

### CODE REVIEW

**Review by dhInmotionSoftware — APPROVED** [review]

**Comment by george-apostu8** [comment]
@wtmoose Can we have this merged?

**Comment by wtmoose** [comment]
I don't have this issue. How are you installing SM?

**Comment by gali8** [comment]
Can you release it?

**Comment by wtmoose** [comment]
@gali8 I don’t have this issue on my M1. I asked for more info above and didn’t get a reply. I’m not going to release this change until I understand what’s going on.

**Comment by gali8** [comment]
Try to install it with SPM, using XCode 14.2 min, do not use rosetta.
Next, start debug on ios simulator.

That's it.

**Comment by wtmoose** [comment]
@gali8 that works for me as well as my colleagues who I asked to try it. Here's the sample project I used. I checked the process in Activity Monitor and verified that I'm not using Rosetta.

[SPMTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/11103087/SPMTest.zip)

**Comment by gali8** [comment]
Ok, found it.
The issue appears when the "Excluded Architectures" is set on "arm64".

Infact the SPMTest works like a charm,

**Pull request closed without merging**
