### PR TITLE
Relocate MainActor from class declaration

### PR DESCRIPTION
**Pull request by kalebzen**
Hi there! We make use of [Resolver](https://github.com/hmlongco/Resolver) for our dependency injection & service locator framework, and our SwiftMessages implementation involves registering our own instance of `SwiftMessages` as one of those dependencies.

When updating to the [latest release](https://github.com/SwiftKickMobile/SwiftMessages/releases/tag/10.0.0) (version 10.0.0), we are being required to annotate our dependency registration code with `@MainActor` due to the changes introduced in [this commit](https://github.com/SwiftKickMobile/SwiftMessages/commit/633b6e593b5730daf9e682cd21f50764bd1e257c). This ultimately requires us to make this change at the entry point of Resolver (which is executed at app launch), meaning we will end up registering **all** of our dependencies on the main thread even though that may not be necessary.

As mentioned on [a separate issue in the Resolver repo](https://github.com/hmlongco/Resolver/issues/150#issuecomment-1099699579) - Even with MainActor annotations, there is no guarantee that the escaping closures will execute on the main thread, which could cause unexpected or inconsistent behavior. ([Additional info on this subject if you're interested](https://mobile.blog/2022/03/28/swift-why-is-my-mainactor-code-running-in-the-background/))

I totally understand the need for having SwiftMessages UI code get executed on the main thread, but I am less sure of the need to require it at the class-level as opposed to limiting it to the functions & properties that truly need to be on the main thread. 

---

With that background out of the way - this PR is for relocating the MainActor annotation from the class level down into each function and property that the compiler requires it on. My implementation is admittedly naive, as I simply removed it from the class declaration and played whack-a-mole with the compiler until it was satisfied, so please let me know if I am making any invalid assumptions or if this may end up regressing the threading behavior that you were trying to fix to begin with.

### CODE REVIEW

**Comment by wtmoose** [comment]
Bro. Why aren't y'all using Factory yet

**Comment by wtmoose** [comment]
@kalebzen instead, would you be willing to wrap your instance in this?

````swift
class MainActorBox<T> {
    init(instance: @escaping @autoclosure @MainActor () -> T) {
        self.factory = instance
    }

    @MainActor
    var instance: T {
        let instance = _instance ?? factory()
        _instance = instance
        return instance
    }

    private let factory: @MainActor () -> T
    @MainActor private var _instance: T?
}
````

Usage:

````swift
@MainActor
struct Foo {}

let foo = MainActorBox { @MainActor in
    Foo()
}

Task { @MainActor in
    foo.instance
}
````

Introducing `@MainActor` helps avoid a common SwiftMessages error of calling the API from a background queue after an API call. I really don't like getting granular with the application of `@MainActor`. It just feels gross to me.

**Comment by wtmoose** [comment]
@kalebzen I noticed the striking header in doc center seems broken lately. Ya'll should check out our new library – I think it could fix that and eliminate a lot of code: https://github.com/SwiftKickMobile/SwiftUIMaterialTabs

**Comment by wtmoose** [comment]
@kalebzen The box type I gave you would be returned by resolver without any need for main actor context. You would only need to be in a main context when accessing the `instance` property. You'd be doing that in a view, presumably, so I would think that solves your problem.

I wrote the sample code in a playground, which doesn't run in main actor context. So it demonstrates that:

1. You can instantiate the box type without being in a main context
2. Once in a main context, you can access the `instance`

Does that make sense or am I mis-understanding the issue?

**Comment by wtmoose** [comment]
Sample project:

[MainActorBox.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/14388577/MainActorBox.zip)

I removed the `@autoclosure` from `MainActorBox` because the compiler was yelling at me and I didn't want to spend time figuring it out.

**Comment by wtmoose** [comment]
@kalebzen curious what your take is on the adapter type. Internal feedback I got was not positive, so I'm considering going with this PR. However, I like the adapter approach because it would work for any `@MainActor` type in general.

**Comment by kalebzen** [comment]
> Does that make sense or am I mis-understanding the issue?

It does make sense - I think I was the one who misunderstood your original suggestion

> @kalebzen curious what your take is on the adapter type. Internal feedback I got was not positive, so I'm considering going with this PR. However, I like the adapter approach because it would work for any `@MainActor` type in general.

I gave it a shot, it does seem to work. I agree it could be used in other spots, but until now we haven't had a use case for something like this. 

I can't help but feel conflicted because it seems like placing MainActor on the class-level ends up shifting the onus of writing a small layer of abstraction like this onto many/all consumers of the library instead of SwiftMessages enforcing MainActor usage on the API's that truly _need_ to be on the main thread. Unless I'm missing the benefits of requiring the class initializer to take place on the main thread, I think the library should ideally aim to impose as few restrictions as possible that are not absolutely necessary.

**Comment by wtmoose** [comment]
@kalebzen I'm planning to make this change. I've been swamped, so not sure exactly when. I'd stay on v9 for now unless you need something specific from v10.

**Review by wtmoose — APPROVED** [review]

**Comment by wtmoose** [comment]
@kalebzen sorry for being slow to release this. It occurred to me that, instead of your changes, we should be able to just make  `SwiftMessages.init()` `nonisolated`. I've made that change on `master`. Could you let me know if this works for you?

**Pull request merged**
