### PR TITLE
Add new config params

### PR DESCRIPTION
**Pull request by bespalown**

### CODE REVIEW

**Comment by bespalown** [comment]
Add new config params

**Comment by wtmoose** [comment]
I appreciate the suggestions, but I'm not sure there is a motivation for either of these options:

1. The `interactiveHide` enables or disables the pan gesture.
2. Nib files are provided for you top copy into your project and make layout adjustments.

**Comment by bespalown** [comment]
Thanks for the answer!

Sorry, I just did not notice interactiveHide.
And the second question I have recorded a video.

On first video 
config {
    .window(windowLevel: UIWindowLevelNormal)
}
and top margin between container view and backgroundView = 64.0

On second video 
config {
    .window(windowLevel: UIWindowLevelNormal)
    .edgeInsets = UIEdgeInsets(top: 64, left: 0, bottom: 0, right: 0)
}

[Archive.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/609709/Archive.zip)

**Comment by wtmoose** [comment]
Couple of questions for you.

1. I see the two videos, but I'm not sure what you're trying to illustrate. Could you elaborate?
2. The second video doesn't look like `.window(windowLevel: UIWindowLevelNormal)` because it's sliding down from below the navigation bar. When you use `.window`, the message is displayed in a separate, temporary window and would not be able to do that. Could you double check your settings?

**Comment by bespalown** [comment]
Yes, I double-checked all the settings several times. EdgeInsets need =) 
I can send your code probably will be clearer.

**Comment by wtmoose** [comment]
Please do. I don't know exactly what you're trying to accomplish, so I don't know how to interpret your videos.

**Comment by wtmoose** [comment]
I'm not sure how to proceed with this because I still don't understand what you're trying to accomplish. The videos are great, but I don't know what they mean without an associated problem description stating desired behavior and actual behavior.

**Comment by wtmoose** [comment]
Closing. No response from poster.

**Pull request closed without merging**
