### PR TITLE
add show/hide listener support

### PR DESCRIPTION
**Pull request by griddle**
I needed to update my UI in certain view controllers based on whether a message was showing or not.

### CODE REVIEW

**Comment by wtmoose** [comment]
Sorry, I forgot to reply to this. Thank you for the input.  I'm going to add a callback in the next major release and I'll consider this proposal when I get to it on my todo list.

**Comment by guillaumebesse** [comment]
It is a very useful feature I really love to have...

My use case is : I want to display a message and once displayed, go back to another view

I try @griddle listeners and it works nice.  
I just need to remove the listener when swiftMessageDidHide is called... 
    
    private let viewController : UIViewController
    
    func swiftMessageDidHide() -> Void {
        _ = viewController.navigationController?.popViewController(animated: true)
        SwiftMessages.removeListener(self)
    }

**Comment by wtmoose** [comment]
@griddle @guillaumebesse please check version 3.1.0 and let me know if this meets your needs. Because listeners are attached to `SwiftMessages.Config`, they can be scoped to individual messages or assigned to `SwiftMessages.defaultConfig` for global default behavior.

**Comment by griddle** [comment]
thanks @wtmoose. I won't have a chance to switch over until next week but it looks great to me.

**Comment by wtmoose** [comment]
FYI in case you've already pulled the changes down...I moved the 3.1.0 tag forward one commit to make `eventListeners` array non-optional.

**Comment by guillaumebesse** [comment]
@wtmoose I integrate today version 3.1.0 with new eventListener feature... It works and it is really great !

I added showMessage func to UIViewController (using extension) with all SwiftMessages configuration init and now I can do  

    self.showMessage(message: msg, listener:  { event in
        if event == .didHide {
             = self.navigationController?.popViewController(animated: true)
        }
    })

Very nice job !! Thank you !!

**Comment by JoshHrach** [comment]
@wtmoose Any ETA on when this will be in a public SwiftMessages release? I'm not seeing the 3.1 release mentioned here.

**Comment by wtmoose** [comment]
@JoshHrach was giving @griddle a chance to test.

**Comment by JoshHrach** [comment]
@wtmoose Got it. Well, I'll be keeping my eyes open. This is exactly what I was looking for with SwiftMessages today. Thankfully, our app isn't going live any time soon, so I am in no rush.

**Comment by wtmoose** [comment]
@JoshHrach I just re-published the 3.1.0 tag. Just noticed that it wasn't on origin.

**Comment by JoshHrach** [comment]
@wtmoose Thanks. I'm installing 3.1 now and will be trying this shortly.

**Comment by JoshHrach** [comment]
I just spent the past half hour with this. It seems to work great. I'll need to optimize how I'm adding the listener, and with my current project, I may want to have a better set of message configs. But that's all things I need to improve on my side. 

Thanks for adding this in!

**Comment by griddle** [comment]
Sorry all, I've been caught up elsewhere in my work. I just tested everything and it works great. I appreciate the quick turnaround on this @wtmoose. 👍

**Comment by wtmoose** [comment]
OK, gents. I've made 3.1.1 (I added a feature since 3.1.0) the current release and pushed to CocoaPods. Thanks for the input!

**Pull request closed without merging**
