### PR TITLE
Prevent usage of UIApplication.shared when building for extensions

### PR DESCRIPTION
**Pull request by ianyh**
It's not accessible at compile-time for anything requiring app extension only APIs.

I'm not totally sure what to do in the extension case to determine a status bar offset. Help with that would be much appreciated.

### CODE REVIEW

**Comment by wtmoose** [comment]
This is already supported in 4.1.3. See #183. Does that work for you?

**Comment by ianyh** [comment]
I encountered the compilation error in 4.1.3, and was able to reproduce it from `master` when using the `APPLICATION_EXTENSION_API_ONLY` flag with the `SWIFTMESSAGES_APP_EXTENSIONS` option and `SWIFTMESSAGES_APP_EXTENSIONS=1` flag applied. #183 caught most of the instances of accessing `UIApplication.shared`, but it seems that one flew under the radar.

**Comment by wtmoose** [comment]
OK gotcha. Looks like a merge problem. I'll take a look

**Comment by ianyh** [comment]
Looking a bit it looks like https://github.com/SwiftKickMobile/SwiftMessages/commit/2f8de41d197138fbb9bedbf1d8a2463863c0bffe#diff-35b0b34aadc8e036ab3c1391c1a79e87 introduced the access after #183 if that is helpful for context.

**Comment by wtmoose** [comment]
Yep, thanks

**Comment by ianyh** [comment]
Oh, good call on the demo app. Happy to help. Thanks!

**Comment by adrianodiasx93** [comment]
@wtmoose, I gonna give the Demo a better look, but right now my project still complains:

>*** Checking out SwiftMessages at "4.1.4"
*** xcodebuild output can be found in /var/folders/0r/swvcjf_545vgcbys5t2nw3zc0000gp/T/carthage-xcodebuild.TRRH4S.log
*** Building scheme "SwiftMessages" in Demo.xcworkspace

>ld: warning: linking against a dylib which is not safe for use in application extensions: /.../Carthage/Build/iOS/SwiftMessages.framework/SwiftMessages

Should it be happening?

**Comment by wtmoose** [comment]
@adrianodiasx93 I'm not clear why you commented on this particular PR?

**Comment by adrianodiasx93** [comment]
@wtmoose at first, it seemed to me this PR would avoid the situation I mentioned.
I am gonna open a issue.

**Pull request merged**
